openapi: 3.0.3
info:
  title: Song Lyrics & Popularity (SLAP)
  description: This API provides the metrics and the metadata of songs in order to analyze Lyrics & Popularity
# #Template for if we want to put any contacts
#  contact:
#    name: Koo Cook
#    url: https://www.koocook.app/api-support/
#    email: koocook.app@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: localhost:8000/api
paths:
  /songs:
    parameters:
      - name: page
        in: query
        description: The page number
        required: false
        schema:
          type: integer
        example: 1
    get:
      description: Returns all songs
      operationId: slap_flask.public.controllers.songs.get_songs
      responses:
        '200':
          description: A list of songs.
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=4
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=2
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Song'
        '404':
          $ref: '#/components/responses/default'
  /song:
    parameters:
      - name: title
        in: query
        description: The title of a song
        required: true
        schema:
          type: string
        example: Begin Again
      - name: artist
        in: query
        description: The artist of a song
        required: true
        schema:
          type: string
        example: Taylor Swift
    get:
      description: Returns a song matching the query
      operationId: slap_flask.public.controllers.songs.get_song
      responses:
        '200':
          description: A list of songs.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Song'
        '404':
          $ref: '#/components/responses/default'
  /songs/{id}/:
    get:
      operationId: retrieveSong
      description: An API endpoint that allows songs to be viewed.
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this song.
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Song'
          description: ''
        '404':
          $ref: '#/components/responses/default'
  /songs/{song_id}/words:
    get:
      operationId: listWords
      description: A list of words in the given song lyrics
      parameters:
        - name: song_id
          in: path
          required: true
          description: ''
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  words:
                    type: array
                    items:
                      type: string
          description: ''
  /songs/{song_id}/word-frequency/plot:
    get:
      operationId: listSongWordFrequencyPlots
      description: ''
      parameters:
        - name: song_id
          in: path
          required: true
          description: ''
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: ''
  /song/{song_id}/metrics:
    parameters:
      - name: song_id
        in: path
        description: The ID of the song
        required: true
        schema:
          type: string
        example: 12
      - name: for_graph
        in: query
        description: Whether to return additional parameters for making a graph
        required: false
        schema:
          type: boolean
        example: true
    get:
      description: Returns song metrics
      operationId: slap_flask.public.controllers.songs.get_song_metrics
      responses:
        '200':
          description: The metrics of a given song
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SongMetrics'
        '404':
          $ref: '#/components/responses/default'
  /song/{song_id}/word_popularity:
    parameters:
      - name: song_id
        in: path
        description: The ID of the song
        required: true
        schema:
          type: string
        example: 519
      - name: word_count_weight
        in: query
        description: The given weight of word count
        required: true
        schema:
          type: number
        example: 12
      - name: popularity_weight
        in: query
        description: The given popularity index of word count
        required: true
        schema:
          type: number
        example: 12
      - name: popularity_indicator
        in: query
        description: The given popularity indicator
        required: false
        schema:
          type: string
        example: youtube_views
    get:
      description: Returns word popularity index
      operationId: slap_flask.public.controllers.songs.get_parameterized_word_popularity_single
      responses:
        '200':
          description: The parameterized word popularity of a given song
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    song_id:
                      type: string
                    score:
                      type: number
        '404':
          $ref: '#/components/responses/default'
  /songs/words/randomize:
    get:
      operationId: listWordRandomizations
      description: ''
      parameters: [ ]
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  word:
                    type: string
          description: ''
  /song/genres:
    get:
      description: Returns all genres
      operationId: slap_flask.public.controllers.songs.get_song_genres
      responses:
        '200':
          description: A list of genres.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Genre'
        '404':
          $ref: '#/components/responses/default'
  /plot/rep-pop:
    parameters:
      - name: pop_facet
        in: query
        description: The page number
        required: false
        schema:
          type: integer
        example: youtube_view
      - name: rep_facet
        in: query
        description: The page number
        required: false
        schema:
          type: integer
        example: compressibility
    get:
      operationId: slap.listRepetitionPopularityPlots
      description: Return a list of all users.
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: ''
  /plot/rep-matrix/{song_id}:
    get:
      operationId: retrieveRepetitionMatrixPlot
      description: 'View to list all users in the system.


          * Requires token authentication.

          * Only admin users are able to access this view.'
      parameters:
        - name: song_id
          in: path
          required: true
          description: ''
          schema:
            type: string
      responses:
        '200':
          content:
            text/csv:
              schema:
                type: string
          description: ''
components:
  schemas:
    HttpError:
      type: object
      properties:
        message:
          type: string
    Song:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        artists:
          type: array
          items:
            type: string
          readOnly: true
        genres:
          type: array
          items:
            type: string
          readOnly: true
        title:
          type: string
          maxLength: 289
        lyrics:
          type: string
        compressibility:
          type: number
        spotify_popularity:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
      required:
        - title
        - lyrics
        - compressibility
        - spotify_popularity
    Artist:
      type: object
      properties:
        name:
          type: string
    SongMetrics:
      type: object
      properties:
        repetition:
          type: object
          properties:
            bow:
              type: object
              properties:
                frequencies:
                  type: array
                  items:
                    type: integer
                words:
                  type: array
                  items:
                    type: string
                ranks:
                  type: array
                  items:
                    type: integer
        chart:
          type: object
          properties:
            library:
              type: string
            type:
              type: string
    Genre:
      type: object
      properties:
        name:
          type: string
        genre_id:
          type: string
  responses:
# Just to test out responses object
    default:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HttpError'
